version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package -DskipTests=true
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/management.jar
  discard-paths: yes

