version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - mvn test
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/management.war
  discard-paths: yes

